from typing import TypedDict, List


class CompilerOptions(TypedDict, total=False):
    allowArbitraryExtensions: bool
    allowEmitOnError: bool
    allowImportingTsExtensions: bool
    allowJs: bool
    allowSyntheticDefaultImports: bool
    allowUmdGlobalAccess: bool
    allowUnreachableCode: bool
    allowUnusedLabels: bool
    alwaysStrict: bool
    assumeChangesOnlyAffectDirectDependencies: bool
    baseUrl: str
    checkJs: bool
    charset: str
    composite: bool
    customConditions: List[str]
    declaration: bool
    declarationDir: str
    declarationMap: bool
    emitBOM: bool
    emitDecoratorMetadata: bool
    emitDeclarationOnly: bool
    esModuleInterop: bool
    exactOptionalPropertyTypes: bool
    experimentalDecorators: bool
    forceConsistentCasingInFileNames: bool
    importHelpers: bool
    incremental: bool
    jsxFactory: str
    jsxFragmentFactory: str
    jsxImportSource: str
    keyofStringsOnly: bool
    lib: List[str]
    locale: str
    mapRoot: str
    maxNodeModuleJsDepth: float
    moduleSuffixes: List[str]
    noEmit: bool
    noEmitHelpers: bool
    noEmitOnError: bool
    noErrorTruncation: bool
    noFallthroughCasesInSwitch: bool
    noImplicitAny: bool
    noImplicitOverride: bool
    noImplicitReturns: bool
    noImplicitThis: bool
    noImplicitUseStrict: bool
    noLib: bool
    noResolve: bool
    noStrictGenericChecks: bool
    noUncheckedIndexedAccess: bool
    noUnusedLocals: bool
    noUnusedParameters: bool
    outFile: str
    outDir: str
    out: str
    preserveConstEnums: bool
    preserveSymlinks: bool
    preserveValueImports: bool
    project: str
    reactNamespace: str
    removeComments: bool
    resolveJsonModule: bool
    resolvePackageJsonExports: bool
    resolvePackageJsonImports: bool
    rootDir: str
    rootDirs: List[str]
    skipDefaultLibCheck: bool
    skipLibCheck: bool
    sourceMap: bool
    sourceRoot: str
    strict: bool
    strictBindCallApply: bool
    strictFunctionTypes: bool
    strictNullChecks: bool
    strictPropertyInitialization: bool
    stripInternal: bool
    suppressExcessPropertyErrors: bool
    suppressImplicitAnyIndexErrors: bool
    traceResolution: bool
    tsBuildInfoFile: str
    types: List[str]
    typeRoots: List[str]
    useDefineForClassFields: bool
    useUnknownInCatchVariables: bool
    verbatimModuleSyntax: bool
